import { useCallback, useEffect, useMemo, useState } from "react";

import { type Preview, type TemplateDetail, type ValidationIssue, type ViewDetail, StudioApi, StudioApiError, type Workspace } from "../studio/api";

type Selection = { kind: "view"; id: string; isNew?: boolean } | { kind: "template"; path: string; isNew?: boolean } | null;
type BackendStatus = "connecting" | "online" | "unavailable";

function defaultApiBaseUrl(): string { return import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000"; }
function emptyView(id = ""): Record<string, unknown> { return { schema_version: 2, id, text: { inline: "" }, keyboard: [] }; }
function value(payload: Record<string, unknown>, key: string): string { return typeof payload[key] === "string" ? payload[key] : ""; }

export function BackendStatusCard({ apiBaseUrl = defaultApiBaseUrl() }: { apiBaseUrl?: string }) {
  const [status, setStatus] = useState<BackendStatus>("connecting"); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let cancelled = false; void fetch(`${apiBaseUrl.replace(/\/$/, "")}/api/v1/health`).then((response) => response.ok ? response.json() : null).then((body) => { if (!cancelled) setStatus(body?.status === "ok" ? "online" : "unavailable"); }).catch(() => { if (!cancelled) setStatus("unavailable"); }); return () => { cancelled = true; }; }, [apiBaseUrl, attempt]);
  const label = status === "online" ? "Backend online" : status === "connecting" ? "Connecting to local backend…" : "Backend unavailable";
  return <span className={`connection connection--${status}`}>{label}{status === "unavailable" && <button type="button" onClick={() => setAttempt((item) => item + 1)}>Retry</button>}</span>;
}

function Explorer({ workspace, selection, select, add }: { workspace: Workspace; selection: Selection; select(value: Selection): void; add(kind: "view" | "template"): void }) {
  return <nav className="explorer" aria-label="Project resources"><div className="explorer__project"><strong>{workspace.name}</strong><small>{workspace.project_root}</small></div><section className="explorer__section"><header><span>Views</span><button type="button" onClick={() => add("view")}>+</button></header>{workspace.views.length === 0 && <p className="explorer__empty">No views</p>}{workspace.views.map((view) => <button key={view.id} type="button" className={selection?.kind === "view" && selection.id === view.id ? "explorer__item explorer__item--active" : "explorer__item"} onClick={() => select({ kind: "view", id: view.id })}>{view.id}<small>{view.source_path}</small></button>)}</section><section className="explorer__section"><header><span>Templates</span><button type="button" onClick={() => add("template")}>+</button></header>{workspace.templates.length === 0 && <p className="explorer__empty">No templates</p>}{workspace.templates.map((template) => <button key={template.path} type="button" className={selection?.kind === "template" && selection.path === template.path ? "explorer__item explorer__item--active" : "explorer__item"} onClick={() => select({ kind: "template", path: template.path })}>{template.path}</button>)}</section></nav>;
}

function ButtonsEditor({ payload, onChange }: { payload: Record<string, unknown>; onChange(value: Record<string, unknown>): void }) {
  const rows = Array.isArray(payload.keyboard) ? payload.keyboard.filter(Array.isArray) as Array<Array<Record<string, unknown>>> : [];
  const update = (next: Array<Array<Record<string, unknown>>>) => onChange({ ...payload, keyboard: next });
  return <fieldset className="keyboard-editor"><legend>Inline keyboard</legend>{rows.map((row, rowIndex) => <div className="v2-buttons" key={rowIndex}>{row.map((button, buttonIndex) => <div className="v2-button" key={buttonIndex}><input aria-label={`Button ${rowIndex + 1}-${buttonIndex + 1} text`} value={value(button, "text")} placeholder="Button text" onChange={(event) => update(rows.map((current, currentIndex) => currentIndex === rowIndex ? current.map((item, itemIndex) => itemIndex === buttonIndex ? { ...item, text: event.target.value } : item) : current))} /><select aria-label={`Button ${rowIndex + 1}-${buttonIndex + 1} action`} value={(button.action as { type?: string } | undefined)?.type ?? "navigate"} onChange={(event) => update(rows.map((current, currentIndex) => currentIndex === rowIndex ? current.map((item, itemIndex) => itemIndex === buttonIndex ? { ...item, action: { type: event.target.value, target: event.target.value === "flow.cancel" ? undefined : "" } } : item) : current))}><option value="navigate">Navigate</option><option value="flow.start">Start flow</option><option value="flow.cancel">Cancel flow</option><option value="flow.event">Flow event</option></select>{(button.action as { type?: string } | undefined)?.type !== "flow.cancel" && <input aria-label={`Button ${rowIndex + 1}-${buttonIndex + 1} target`} value={((button.action as { target?: string } | undefined)?.target) ?? ""} placeholder="Target" onChange={(event) => update(rows.map((current, currentIndex) => currentIndex === rowIndex ? current.map((item, itemIndex) => itemIndex === buttonIndex ? { ...item, action: { ...(item.action as object), target: event.target.value } } : item) : current))} />}<button type="button" className="button--quiet" onClick={() => update(rows.map((current, currentIndex) => currentIndex === rowIndex ? current.filter((_, itemIndex) => itemIndex !== buttonIndex) : current))}>×</button></div>)}<button type="button" className="button--quiet" onClick={() => update(rows.map((current, currentIndex) => currentIndex === rowIndex ? [...current, { text: "", action: { type: "navigate", target: "" } }] : current))}>Add button</button><button type="button" className="button--quiet" onClick={() => update(rows.filter((_, currentIndex) => currentIndex !== rowIndex))}>Remove row</button></div>)}<button type="button" className="button--quiet" onClick={() => update([...rows, []])}>Add row</button></fieldset>;
}

function ViewEditor({ draft, change, rawValidity }: { draft: ViewDetail & { isNew?: boolean }; change(value: ViewDetail & { isNew?: boolean }): void; rawValidity(valid: boolean): void }) {
  const [mode, setMode] = useState<"form" | "raw">("form"); const [raw, setRaw] = useState(JSON.stringify(draft.payload, null, 2)); const [rawError, setRawError] = useState("");
  useEffect(() => { setMode("form"); setRaw(JSON.stringify(draft.payload, null, 2)); setRawError(""); rawValidity(true); }, [draft.id, draft.revision, rawValidity]);
  const update = (payload: Record<string, unknown>) => change({ ...draft, id: value(payload, "id") || draft.id, payload });
  const text = draft.payload.text as { inline?: string; template?: string } | undefined; const useTemplate = typeof text?.template === "string";
  const unknown = Object.keys(draft.payload).filter((key) => !["schema_version", "id", "text", "keyboard"].includes(key));
  return <section className="editor"><header className="editor__header"><div><p className="eyebrow">v2 view</p><h2>{draft.isNew ? "New view" : draft.id}</h2><small>{draft.source_path || "views/<id>.json"}</small></div><div className="tabs"><button className={mode === "form" ? "tab tab--active" : "tab"} type="button" onClick={() => setMode("form")}>Form</button><button className={mode === "raw" ? "tab tab--active" : "tab"} type="button" onClick={() => setMode("raw")}>Raw JSON</button></div></header>{unknown.length > 0 && <p className="notice">Unknown fields remain intact: {unknown.join(", ")}.</p>}{mode === "raw" ? <label className="editor__raw">View JSON<textarea value={raw} onChange={(event) => { const next = event.target.value; setRaw(next); try { const parsed = JSON.parse(next); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("View must be a JSON object."); update(parsed as Record<string, unknown>); setRawError(""); rawValidity(true); } catch (error) { setRawError(error instanceof Error ? error.message : "Invalid JSON"); rawValidity(false); } }} />{rawError && <small className="error">{rawError}</small>}</label> : <div className="form-grid"><label>View id<input disabled={!draft.isNew} value={draft.id} onChange={(event) => change({ ...draft, id: event.target.value, payload: { ...draft.payload, id: event.target.value } })} /></label><label>Text source<select value={useTemplate ? "template" : "inline"} onChange={(event) => update({ ...draft.payload, text: event.target.value === "template" ? { template: "home.txt" } : { inline: "" } })}><option value="inline">Inline text</option><option value="template">Template file</option></select></label><label>{useTemplate ? "Template path" : "Inline text"}<textarea value={useTemplate ? text?.template ?? "" : text?.inline ?? ""} onChange={(event) => update({ ...draft.payload, text: useTemplate ? { template: event.target.value } : { inline: event.target.value } })} /></label><ButtonsEditor payload={draft.payload} onChange={update} /></div>}</section>;
}

function TemplateEditor({ draft, change }: { draft: TemplateDetail & { isNew?: boolean }; change(value: TemplateDetail & { isNew?: boolean }): void }) { return <section className="editor"><header className="editor__header"><div><p className="eyebrow">v2 template</p><h2>{draft.isNew ? "New template" : draft.path}</h2></div></header><div className="form-grid"><label>Relative .txt path<input disabled={!draft.isNew} value={draft.path} onChange={(event) => change({ ...draft, path: event.target.value })} /></label><label className="editor__raw">Template<textarea value={draft.content} onChange={(event) => change({ ...draft, content: event.target.value })} /></label></div></section>; }

function PreviewPanel({ preview, issues }: { preview: Preview | null; issues: ValidationIssue[] }) { return <aside className="preview" aria-label="Telegram preview"><header><p className="eyebrow">Static preview</p><h2>Telegram</h2></header>{preview ? <><article className="telegram-message">{preview.text || <em>No text yet</em>}</article>{preview.keyboard.map((row, rowIndex) => <div className="telegram-row" key={rowIndex}>{row.map((button, buttonIndex) => <span key={buttonIndex}>{button.text}</span>)}</div>)}{preview.warnings.map((warning) => <p className="warning" key={warning}>{warning}</p>)}</> : <p className="preview__empty">Select a view to preview it.</p>}<section className="issues"><h3>Validation</h3>{issues.length ? issues.map((issue, index) => <p className={issue.level === "error" ? "error" : "warning"} key={`${issue.code}-${index}`}>{issue.message}<small>{issue.source_path}</small></p>) : <p>No issues reported.</p>}</section></aside>; }

export function App({ apiBaseUrl = defaultApiBaseUrl() }: { apiBaseUrl?: string }) {
  const api = useMemo(() => new StudioApi(apiBaseUrl), [apiBaseUrl]); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [selection, setSelection] = useState<Selection>(null); const [view, setView] = useState<(ViewDetail & { isNew?: boolean }) | null>(null); const [template, setTemplate] = useState<(TemplateDetail & { isNew?: boolean }) | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [issues, setIssues] = useState<ValidationIssue[]>([]); const [openPath, setOpenPath] = useState(""); const [parent, setParent] = useState(""); const [name, setName] = useState("my-v2-bot"); const [error, setError] = useState(""); const [conflict, setConflict] = useState(false); const [rawValid, setRawValid] = useState(true); const [busy, setBusy] = useState(false);
  const report = (caught: unknown) => { setError(caught instanceof Error ? caught.message : "Unexpected error"); setConflict(caught instanceof StudioApiError && caught.status === 409); };
  const load = useCallback(async (operation: () => Promise<Workspace>) => { setBusy(true); try { const next = await operation(); setWorkspace(next); setSelection(null); setView(null); setTemplate(null); setPreview(null); setIssues([]); setError(""); } catch (caught) { report(caught); } finally { setBusy(false); } }, []);
  const refresh = useCallback(async () => { if (workspace) setWorkspace(await api.describe(workspace.project_id)); }, [api, workspace]);
  useEffect(() => { if (!workspace || !selection) return; let cancelled = false; void (async () => { try { if (selection.kind === "view") { setTemplate(null); if (selection.isNew) setView({ id: "", source_path: "", revision: "", payload: emptyView(""), isNew: true }); else { const detail = await api.getView(workspace.project_id, selection.id); if (!cancelled) setView(detail); } } else { setView(null); setPreview(null); if (selection.isNew) setTemplate({ path: "new-template.txt", content: "", revision: "", isNew: true }); else { const detail = await api.getTemplate(workspace.project_id, selection.path); if (!cancelled) setTemplate(detail); } } } catch (caught) { if (!cancelled) report(caught); } })(); return () => { cancelled = true; }; }, [api, selection, workspace]);
  useEffect(() => { if (!workspace || !view) return; let cancelled = false; void api.preview(workspace.project_id, view.payload).then((next) => { if (!cancelled) setPreview(next); }).catch((caught) => { if (!cancelled) report(caught); }); return () => { cancelled = true; }; }, [api, view, workspace]);
  const pick = async (set: (value: string) => void) => { const picked = await window.studioDesktop?.selectDirectory(); if (picked) set(picked); };
  const saveView = async () => { if (!workspace || !view) return; setBusy(true); try { const saved = view.isNew ? await api.createView(workspace.project_id, view.id, { ...view.payload, id: view.id, schema_version: 2 }) : await api.saveView(workspace.project_id, view.id, view.payload, view.revision); setView(saved); setSelection({ kind: "view", id: saved.id }); await refresh(); } catch (caught) { report(caught); } finally { setBusy(false); } };
  const saveTemplate = async () => { if (!workspace || !template) return; setBusy(true); try { const saved = await api.saveTemplate(workspace.project_id, template.path, template.content, template.isNew ? undefined : template.revision); setTemplate(saved); setSelection({ kind: "template", path: saved.path }); await refresh(); } catch (caught) { report(caught); } finally { setBusy(false); } };
  const removeView = async () => { if (!workspace || !view || view.isNew || !window.confirm(`Delete '${view.id}'?`)) return; try { await api.deleteView(workspace.project_id, view.id, view.revision); setView(null); setSelection(null); await refresh(); } catch (caught) { report(caught); } };
  if (!workspace) return <main className="welcome"><section><p className="eyebrow">Core v2 Project Studio</p><h1>Telegram Bot Studio</h1><p>Edit explicit v2 views and templates, or generate a standalone v2 bot.</p><BackendStatusCard apiBaseUrl={apiBaseUrl} />{error && <p className="error">{error}</p>}<div className="welcome__actions"><label>Existing v2 project<input value={openPath} onChange={(event) => setOpenPath(event.target.value)} placeholder="C:\\projects\\my-bot" /></label><div><button type="button" className="button--quiet" onClick={() => void pick(setOpenPath)}>Choose…</button><button type="button" disabled={!openPath || busy} onClick={() => void load(() => api.open(openPath))}>Open project</button></div></div><div className="welcome__actions"><label>New v2 project name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Parent directory<input value={parent} onChange={(event) => setParent(event.target.value)} /></label><div><button type="button" className="button--quiet" onClick={() => void pick(setParent)}>Choose parent…</button><button type="button" disabled={!parent || !name || busy} onClick={() => void load(() => api.create(parent, name))}>Create v2 starter</button></div></div></section></main>;
  return <main className="studio"><header className="topbar"><div><strong>Telegram Bot Studio</strong><small>{workspace.resource_root}</small></div><BackendStatusCard apiBaseUrl={apiBaseUrl} /><div><button type="button" className="button--quiet" onClick={() => void refresh()}>Refresh</button><button type="button" onClick={() => void api.validate(workspace.project_id).then(setIssues).catch(report)}>Validate</button></div></header>{error && <p className="global-error">{error}{conflict && <button type="button" onClick={() => { setError(""); setConflict(false); void refresh().catch(report); }}>Reload from disk</button>}<button type="button" onClick={() => setError("")}>×</button></p>}<div className="workspace"><Explorer workspace={workspace} selection={selection} select={setSelection} add={(kind) => setSelection(kind === "view" ? { kind, id: "", isNew: true } : { kind, path: "", isNew: true })} /><section className="workspace__main">{view ? <><ViewEditor draft={view} change={setView} rawValidity={setRawValid} /><footer className="editor__actions"><button type="button" disabled={busy || !rawValid || !view.id} onClick={() => void saveView()}>{view.isNew ? "Create view" : "Save view"}</button>{!view.isNew && <button type="button" className="button--danger" onClick={() => void removeView()}>Delete</button>}</footer></> : template ? <><TemplateEditor draft={template} change={setTemplate} /><footer className="editor__actions"><button type="button" disabled={busy || !template.path} onClick={() => void saveTemplate()}>{template.isNew ? "Create template" : "Save template"}</button></footer></> : <div className="workspace__empty"><h2>Select a v2 resource</h2><p>Choose a view or template from the explorer.</p></div>}</section><PreviewPanel preview={preview} issues={issues} /></div></main>;
}
