from __future__ import annotations

from pipubot.domains.tutoring.enums.enums import (
    ExamTrack,
    SchoolGrade,
    StudyFormat,
    StudyLanguage,
)

from .enum_aliases import (
    EXAM_TRACK_ALIASES,
    SCHOOL_GRADE_ALIASES,
    STUDY_FORMAT_ALIASES,
    STUDY_LANGUAGE_ALIASES,
)
from .field_spec import StudentFieldSpec
from .parsers import (
    deserialize_date,
    deserialize_decimal,
    format_enum,
    make_enum_deserializer,
    make_enum_parser,
    make_enum_serializer,
    parse_date_iso,
    parse_decimal,
    parse_int,
    parse_text,
    serialize_date,
    serialize_decimal,
    validate_positive_decimal,
    validate_positive_int,
)


STUDENT_FIELD_SPECS: tuple[StudentFieldSpec, ...] = (
    StudentFieldSpec(
        field_name="full_name",
        label="Имя",
        aliases=("имя", "name", "фио", "full_name"),
        parser=parse_text,
        required=True,
        allow_positional=True,
    ),
    StudentFieldSpec(
        field_name="default_rate",
        label="Ставка",
        aliases=("ставка", "rate", "цена", "default_rate"),
        parser=parse_decimal,
        required=True,
        allow_positional=True,
        serializer=serialize_decimal,
        deserializer=deserialize_decimal,
        validator=validate_positive_decimal,
    ),
    StudentFieldSpec(
        field_name="default_duration_min",
        label="Длительность урока (в минутах)",
        aliases=(
            "длительность",
            "длительность урока",
            "длительность урока (в минутах)",
            "duration",
            "minutes",
            "default_duration_min",
        ),
        parser=parse_int,
        allow_positional=True,
        validator=validate_positive_int,
    ),
    StudentFieldSpec(
        field_name="telegram_link",
        label="Telegram ссылка",
        aliases=(
            "телеграм ссылка",
            "ссылка на телеграм",
            "телеграм",
            "telegram",
            "telegram link",
            "telegram_link",
        ),
        parser=parse_text,
        allow_positional=True,
    ),
    StudentFieldSpec(
        field_name="email",
        label="Email",
        aliases=("почта", "email"),
        parser=parse_text,
        allow_positional=True,
    ),
    StudentFieldSpec(
        field_name="google_drive_link",
        label="Google Drive ссылка",
        aliases=(
            "гугл диск",
            "гугл диск ссылка",
            "google drive",
            "google drive link",
            "google_drive_link",
        ),
        parser=parse_text,
        allow_positional=True,
    ),
    StudentFieldSpec(
        field_name="school_grade",
        label="Класс",
        aliases=("класс", "grade", "school_grade"),
        parser=make_enum_parser(
            SchoolGrade,
            field_label="Класс",
            aliases=SCHOOL_GRADE_ALIASES,
        ),
        allow_positional=True,
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(SchoolGrade),
    ),
    StudentFieldSpec(
        field_name="exam_track",
        label="Направление экзамена",
        aliases=("направление экзамена", "экзамен", "exam_track"),
        parser=make_enum_parser(
            ExamTrack,
            field_label="Направление экзамена",
            aliases=EXAM_TRACK_ALIASES,
        ),
        allow_positional=True,
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(ExamTrack),
    ),
    StudentFieldSpec(
        field_name="study_language",
        label="Язык обучения",
        aliases=("язык обучения", "язык", "study_language"),
        parser=make_enum_parser(
            StudyLanguage,
            field_label="Язык обучения",
            aliases=STUDY_LANGUAGE_ALIASES,
        ),
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(StudyLanguage),
    ),
    StudentFieldSpec(
        field_name="study_format",
        label="Формат занятий",
        aliases=("формат занятий", "формат", "study_format"),
        parser=make_enum_parser(
            StudyFormat,
            field_label="Формат занятий",
            aliases=STUDY_FORMAT_ALIASES,
        ),
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(StudyFormat),
    ),
    StudentFieldSpec(
        field_name="planned_hours_per_week",
        label="План часов в неделю",
        aliases=(
            "план часов в неделю",
            "часы в неделю",
            "planned_hours_per_week",
        ),
        parser=parse_decimal,
        serializer=serialize_decimal,
        deserializer=deserialize_decimal,
        validator=validate_positive_decimal,
    ),
    StudentFieldSpec(
        field_name="started_on",
        label="Дата начала",
        aliases=("дата начала", "started_on", "start date"),
        parser=parse_date_iso,
        serializer=serialize_date,
        deserializer=deserialize_date,
    ),
    StudentFieldSpec(
        field_name="notes",
        label="Заметки",
        aliases=("заметки", "notes"),
        parser=parse_text,
    ),
)