"""Shared project model used by both runtime and Studio."""

from .loader import ProjectLoadError, ProjectLoader
from .inspection import HandlerSourceInspection, inspect_handler_source
from .references import (
    HandlerUsage,
    VariableUsage,
    find_handler_usages,
    find_variable_usages,
)
from .models import (
    ActionSpec,
    BotManifest,
    ButtonSpec,
    CommandSpec,
    CommandsSpec,
    Diagnostic,
    FlowLifecycle,
    FlowSpec,
    HandlerBinding,
    HandlerInvocation,
    ProjectDefinition,
    ScheduleSpec,
    StateSpec,
    ViewSpec,
    VariableDefinition,
    VariableOwner,
    VARIABLE_OWNER_TYPES,
    VARIABLE_PERSISTENCE,
    VARIABLE_SOURCES,
    VARIABLE_TYPES,
    VARIABLE_UNSET,
)
from .validation import (
    ProjectValidationError,
    load_and_validate_project,
    validate_project,
)

__all__ = [
    "ActionSpec",
    "BotManifest",
    "ButtonSpec",
    "CommandSpec",
    "CommandsSpec",
    "Diagnostic",
    "FlowLifecycle",
    "FlowSpec",
    "HandlerBinding",
    "HandlerInvocation",
    "HandlerSourceInspection",
    "HandlerUsage",
    "VariableUsage",
    "ProjectDefinition",
    "ProjectLoadError",
    "ProjectLoader",
    "ProjectValidationError",
    "ScheduleSpec",
    "StateSpec",
    "ViewSpec",
    "VariableDefinition",
    "VariableOwner",
    "VARIABLE_OWNER_TYPES",
    "VARIABLE_PERSISTENCE",
    "VARIABLE_SOURCES",
    "VARIABLE_TYPES",
    "VARIABLE_UNSET",
    "load_and_validate_project",
    "validate_project",
    "find_handler_usages",
    "find_variable_usages",
    "inspect_handler_source",
]
