from __future__ import annotations

from core.interaction.ui.components.process.patterns.draft_create_process import FieldSpec
from pipubot.domains.tutoring.students.results import StudentDraft
from pipubot.domains.tutoring.enums.student import SchoolGrade, ExamTrack, StudyLanguage, StudyFormat

from .enum_aliases import (
    EXAM_TRACK_ALIASES,
    SCHOOL_GRADE_ALIASES,
    STUDY_FORMAT_ALIASES,
    STUDY_LANGUAGE_ALIASES,
)
from .parsers import (
    deserialize_date,
    deserialize_decimal,
    format_enum,
    make_enum_deserializer,
    make_enum_parser,
    make_enum_serializer,
    parse_date_iso,
    parse_decimal,
    parse_int,
    parse_text,
    positive_decimal_validator,
    positive_int_validator,
    serialize_date,
    serialize_decimal,
)

STUDENT_FIELD_SPECS: tuple[FieldSpec[StudentDraft, object], ...] = (
    FieldSpec.build(
        name="full_name",
        label="Имя",
        aliases=("имя", "name", "фио"),
        parser=parse_text,
        required=True,
        positional=True,
    ),
    FieldSpec.build(
        name="default_rate",
        label="Ставка",
        aliases=("ставка", "rate", "цена"),
        parser=parse_decimal,
        required=True,
        positional=True,
        serializer=serialize_decimal,
        deserializer=deserialize_decimal,
        validator=positive_decimal_validator,
    ),
    FieldSpec.build(
        name="default_duration_min",
        label="Длительность урока (в минутах)",
        aliases=(
            "длительность",
            "длительность урока",
            "длительность урока (в минутах)",
            "duration",
            "minutes",
        ),
        parser=parse_int,
        positional=True,
        validator=positive_int_validator,
    ),
    FieldSpec.build(
        name="telegram_link",
        label="Telegram ссылка",
        aliases=(
            "телеграм ссылка",
            "ссылка на телеграм",
            "телеграм",
            "telegram",
            "telegram link",
        ),
        parser=parse_text,
        positional=True,
    ),
    FieldSpec.build(
        name="email",
        label="Email",
        aliases=("почта",),
        parser=parse_text,
        positional=True,
    ),
    FieldSpec.build(
        name="google_drive_link",
        label="Google Drive ссылка",
        aliases=(
            "гугл диск",
            "гугл диск ссылка",
            "google drive",
            "google drive link",
        ),
        parser=parse_text,
        positional=True,
    ),
    FieldSpec.build(
        name="school_grade",
        label="Класс",
        aliases=("класс", "grade"),
        parser=make_enum_parser(
            SchoolGrade,
            field_label="Класс",
            aliases=SCHOOL_GRADE_ALIASES,
        ),
        positional=True,
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(SchoolGrade),
    ),
    FieldSpec.build(
        name="exam_track",
        label="Направление экзамена",
        aliases=("направление экзамена", "экзамен"),
        parser=make_enum_parser(
            ExamTrack,
            field_label="Направление экзамена",
            aliases=EXAM_TRACK_ALIASES,
        ),
        positional=True,
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(ExamTrack),
    ),
    FieldSpec.build(
        name="study_language",
        label="Язык обучения",
        aliases=("язык обучения", "язык"),
        parser=make_enum_parser(
            StudyLanguage,
            field_label="Язык обучения",
            aliases=STUDY_LANGUAGE_ALIASES,
        ),
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(StudyLanguage),
    ),
    FieldSpec.build(
        name="study_format",
        label="Формат занятий",
        aliases=("формат занятий", "формат"),
        parser=make_enum_parser(
            StudyFormat,
            field_label="Формат занятий",
            aliases=STUDY_FORMAT_ALIASES,
        ),
        formatter=format_enum,
        serializer=make_enum_serializer(),
        deserializer=make_enum_deserializer(StudyFormat),
    ),
    FieldSpec.build(
        name="planned_hours_per_week",
        label="План часов в неделю",
        aliases=("план часов в неделю", "часы в неделю"),
        parser=parse_decimal,
        serializer=serialize_decimal,
        deserializer=deserialize_decimal,
        validator=positive_decimal_validator,
    ),
    FieldSpec.build(
        name="started_on",
        label="Дата начала",
        aliases=("дата начала", "start date"),
        parser=parse_date_iso,
        serializer=serialize_date,
        deserializer=deserialize_date,
        positional=False,
    ),
    FieldSpec.build(
        name="notes",
        label="Заметки",
        aliases=("заметки",),
        parser=parse_text,
        positional=False,
    ),
    FieldSpec.build(
        name="default_currency",
        label="Валюта",
        aliases=(
            "валюта",
            "currency",
        ),
        parser=parse_text,
        positional=False,
    ),
)