from __future__ import annotations
from typing import Protocol, Any


class StateStore(Protocol):
    def set(self, key: Any, value: Any) -> None: ...
    def get(self, key: Any, default: Any = None) -> Any: ...
    def pop(self, key: Any, default: Any = None) -> Any: ...
    def has(self, key: Any) -> bool: ...
    def dump(self) -> dict: ...
