from __future__ import annotations

from pathlib import Path
from typing import Protocol, Sequence

from ..flow import Flow
from ..project import BotProject, ProjectTreeEntry, RecentProject


class ProjectRepository(Protocol):
    def create(self, root: Path, project: BotProject) -> BotProject: ...
    def open(self, root: Path) -> BotProject: ...
    def save_project(self, root: Path, project: BotProject) -> None: ...

    def list_flows(self, root: Path) -> Sequence[Flow]: ...
    def load_flow(self, root: Path, flow_id: str) -> Flow: ...
    def save_flow(self, root: Path, flow: Flow) -> None: ...
    def delete_flow(self, root: Path, flow_id: str) -> None: ...

    def list_scripts(self, root: Path) -> Sequence[str]: ...
    def read_script(self, root: Path, relative_path: str) -> str: ...
    def save_script(self, root: Path, relative_path: str, content: str) -> None: ...
    def rename_script(self, root: Path, relative_path: str, new_path: str) -> None: ...
    def delete_script(self, root: Path, relative_path: str) -> None: ...

    def list_assets(self, root: Path) -> Sequence[str]: ...
    def read_asset(self, root: Path, relative_path: str) -> bytes: ...
    def save_asset(self, root: Path, relative_path: str, content: bytes) -> None: ...
    def rename_asset(self, root: Path, relative_path: str, new_path: str) -> None: ...
    def delete_asset(self, root: Path, relative_path: str) -> None: ...
    def tree(self, root: Path) -> Sequence[ProjectTreeEntry]: ...


class RecentProjectsRepository(Protocol):
    def list(self) -> Sequence[RecentProject]: ...
    def add(self, project: RecentProject) -> None: ...
    def remove(self, project_id: str) -> None: ...
